name: tabata_timer
description: Tabata training interval timer.

version: 1.2.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.13.2
  auto_size_text: ^2.1.0
  flutter_colorpicker: ^0.2.6
  numberpicker: ^1.1.0
  screen: ^0.0.5
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/boop.mp3
  - assets/dingdingding.mp3
  - assets/pip.mp3