name: tabata_timer
description: Tabata training interval timer.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.8.0
  auto_size_text: ^0.3.0
  flutter_colorpicker: ^0.2.1
  numberpicker: ^1.0.0
  screen: ^0.0.4
  shared_preferences: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/boop.mp3
  - assets/dingdingding.mp3
  - assets/pip.mp3