name: tabata_timer
description: Tabata training interval timer.

version: 1.3.1+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.14.2
  auto_size_text: ^2.1.0
  flutter_colorpicker: ^0.3.2
  numberpicker: ^1.2.0
  screen: ^0.0.5
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/boop.mp3
  - assets/dingdingding.mp3
  - assets/pip.mp3
